services:
  quotes-api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quotes-api-tests
    volumes:
      - ./build/reports:/app/build/reports
      - ./build/allure-results:/app/build/allure-results
    environment:
      - GRADLE_OPTS=-Dorg.gradle.daemon=false